# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RiderBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RiderBook
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Swinject', '~> 2.6.2'
	
  target 'RiderBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RiderBookUITests' do
    # Pods for testing
  end

end
